# Generated by Django 3.1.3 on 2020-12-10 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_good', models.ImageField(upload_to='units/')),
                ('name_of_good', models.CharField(max_length=250)),
                ('mass_of_good_in_kgs', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groceapp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='groceapp.userprofile')),
            ],
        ),
    ]
